// This file was generated by Prisma, and assumes you run Prisma commands using `bun --bun run prisma [command]`.
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "bun prisma/seed.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
    // Only `migrate dev` needs a shadow database; production runs
    // `migrate deploy`, which doesn't, so this is optional (env() would
    // throw when it's unset).
    shadowDatabaseUrl: process.env.SHADOW_DATABASE_URL,
  },
});
